# Generated by Django 3.2.8 on 2022-03-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classify',
            fields=[
                ('classify_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-classify_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('stock', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=50)),
                ('cover_pic', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='vitawebsite_front/scr/image/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_user_id', to='home.user')),
            ],
            options={
                'ordering': ('-modify_time',),
            },
        ),
    ]
