# Generated by Django 3.1.7 on 2021-11-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(max_length=8)),
                ('payment_state', models.BooleanField(default=False)),
            ],
        ),
    ]
