# Generated by Django 3.1.7 on 2021-11-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('payment_state', models.BooleanField(default=False)),
                ('order_number', models.IntegerField(max_length=8)),
            ],
        ),
    ]
