# Generated by Django 3.1.7 on 2021-11-21 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify_name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_list', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('payment_statue', models.BooleanField(default=0)),
                ('send_mail', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('order_number', models.IntegerField()),
                ('member_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(unique=True)),
                ('price', models.IntegerField()),
                ('payment_statue', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=50)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('stock', models.BooleanField(default=1)),
                ('category_id', models.IntegerField()),
                ('cover_pic', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('update_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
