# Generated by Django 3.2.8 on 2022-02-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220224_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classify',
            options={'ordering': ('-classify_name',)},
        ),
    ]
